version: "2"

linters:
  enable:
    - errcheck
    - staticcheck
    - unused
    - govet
    - ineffassign
  settings:
    errcheck:
      check-blank: false
      check-type-assertions: false

run:
  timeout: 5m
  tests: true
